# Generated by Django 3.2.12 on 2022-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название учетки')),
                ('email', models.TextField(verbose_name='Имя пользователя')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
        ),
    ]
